# .github/dependabot.yml

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of workflow files
    schedule:
      # Check for updates to actions every week
      interval: "daily"
    commit-message:
      # Add a prefix to the commit message for clarity
      prefix: "chore"
    reviewers:
      # Automatically request a review from your GitHub username
      - "arnabaich"
      
